### PR TITLE
Add letsencrypt issuer in docker image

### PR DESCRIPTION
**Pull request by mms-gianni**
This feature will enable users to get a letsencrypt SSL certificate inside the docker image. 

New introducen ENV vars: 
- LETSENCRYPT_ENABLED => Enable Letsencrypt
- LETSENCRYPT_PORT => Letsencrypt ACME port

### CODE REVIEW

**Comment by dlen** [comment]
Hi @mms-gianni!

Thanks for your submission!! I will review it in the upcoming days.

**Comment by dlen** [comment]
HI @mms-gianni and sorry for the delay!

What is the benefit you seek with this PR over using a reverse proxy such as traefik to handle the LE automation?
I'm a bit reluctant to add certbot due to the dependencies it will introduce on the image :(

**Comment by mms-gianni** [comment]
You are right: Proxies like Traefik or ingress-nginx with a certmanager solves this too. And I see your concerns.

This configuration is useful, when running docker without kubernetes on a baremetal installation.

**Comment by dlen** [comment]
Yeah, I see. But even on baremetal escenarios there is nothing preventing you to run traefik on top with a docker-compose stack for instance.
I really appreciate your contribution and I think it is well executed but it looks like a task that can be done outside the passbolt container easily.

I don't like to reject good contributions so I won't close the PR in case more people land here and becomes more requested by the community. In that case we will merge it so you will still be the author.

Thanks for your time!

**Pull request closed without merging**
