### PR TITLE
add wait-for.sh to Dockerfile

### PR DESCRIPTION
**Pull request by elisiariocouto**
I've added the `wait-for.sh` script to the base Docker image. This script is always needed, so it should be bundled with the rest of the components.

### CODE REVIEW

**Comment by dlen** [comment]
Hi @elisiariocouto thanks for your submission and for your interest in the project!

Following my thoughts:

I'm a bit reluctant to add wait-for.sh to the base image. I would rather to just add to docker-compose.yml:
```
restart: on-failure
```
This way we would let passbolt container restart until it can connect to mariadb/mysql/place_your_database_engine_here which I guess it should have been the way to go from the beginning instead of adding wait-for.sh to the repo.

The `restart: on-failure` approach seems more convenient to me because:
- It won't convolute passbolt container boot process more than it actually is
- It is a common pattern what most container orchestrators do run -> fail -> restart -> backoff

Also we are only talking about the relational database backend but you could run passbolt using redis as a cache engine would that mean that we should add a check on wait-for.sh for this?

As a different option we could even embed a simplified version of wait-for.sh into the docker-compose.yml file instead of distributing it as a separated script. I rather the on-failure method though.

I would like to hear your feedback!

**Comment by elisiariocouto** [comment]
Hello @dlen. Thanks for your comment on this and congratulations on the project. I've been using it for almost a year and it keeps getting better!

Regarding the `wait-for.sh` script: my only problem with this is that I need to make sure that the script was not updated on every passbolt release. I use Ansible to automate the deployment to our infrastructure, and this manual step of checking if the `wait-for.sh` script did not change or replace it with a newer version is not necessary if it is bundled in the docker image.
I see that the boot process is already heavy enough and this might not be the best option.
On the other hand, in the [Docker Compose documentation](https://docs.docker.com/compose/startup-order/) they state that a custom wrapper like `wait-for.sh` should be added on services like this.
On a final note on this option, we can choose to not use the script if we don't have a relational database backend simply by not modifying the `command` option in the `docker-compose.yml`.

Regarding the `on-failure` restart: is this safe enough? I've saw that on the `docker-entrypoint.sh` you are already exiting in case of failures with `set -euo pipefail`. My only fear is skipping migrations but I don't think this will happen.

If you think that the `restart: on-failure` option is safe enough for not skipping migrations or break the normal startup, I will close this merge request and open a new one with this option.

Thanks

**Comment by dlen** [comment]
Hi @elisiariocouto thanks for your kind comments! It is always a pleasure to see the work is useful for others, muito obrigado!

Regarding your feedback I see your problem but I don't have any more bandwidth this week to take care of this PR. I would like to perform some testing on some other scenarios than yours, probably next week I will keep you posted.

**Comment by dlen** [comment]
Just for your information yesterday I conducted some tests with `restart: on-failure` that where successful both with new empty database and with an already created database pending of migration.

**Comment by dlen** [comment]
Thanks for your contribution @elisiariocouto :blue_heart: 
I decided to merge it as it is a nice to have for some use cases such as yours and it won't prevent anybody to use the `restart: on-failure` approach
In the future I would like to get rid of wait-for.sh though.

**Comment by elisiariocouto** [comment]
Thanks @dlen !
Keep up the good work

**Pull request merged**
