### PR TITLE
change to LABEL, add docker-compose file for testing

### PR DESCRIPTION
**Pull request by ben-st**
i added a docker-compose.yml file for quick tests.
It is IMHO easier, since you don't need the container IP Adress.
It works with DNS, since both containers are in the same network.
I also changed MAINTAINER to LABEL since former is deprecated as of Docker 1.13
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

### CODE REVIEW

**Comment by ben-st** [comment]
@dlen i saw a little bit too late you already created a compose file in your repo.
I would love to see it in the Docker Hub repo ;)

You can update the LABEL and close the PR if you like and we use your compose file, that would be totally fine for me.

**Comment by dlen** [comment]
Hi @ben-st thanks a lot for your feedback! There is an open discussion going on about promoting the passbolt-compose I wrote as an official passbolt compose. You are right that we could, at least, mention it on the README (even if it doesn't make it as an official tool) so people can use it as a template to easily launch passbolt.
Thanks for your PR, most the maintainer deprecation change will be merged but not the docker-compose file. That kind of content (a composer setup) is out of the scope of this repository.

**Comment by ivangretsky** [comment]
Good day! Found this issue looking foe an easy docker-compose/docker stack setup.
> That kind of content (a composer setup) is out of the scope of this repository.
Why is composer setup out of scope? Iy seems to be way easier for a newbee like me.

**Comment by dlen** [comment]
Hello @ivangretsky there is a passbolt-composer here: https://github.com/dlen/passbolt-compose
Please feel free to check it out

**Comment by ivangretsky** [comment]
Nice!
Why not put it under the passbolt organization umbrella?

**Pull request closed without merging**
